version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: [ "dependencies", "github-actions" ]
    assignees: [ "LVMVRQUXL" ]
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/"
    labels: [ "dependencies", "gradle" ]
    assignees: [ "LVMVRQUXL" ]
    schedule:
      interval: "monthly"
