name: Delivery (types4)
on:
  workflow_dispatch:
env:
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
  GIT_USER: ${{ secrets.GIT_USER }}
  GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
jobs:
  delivery:
    name: Publication to OSSRH
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.1
      - name: Setup Java
        uses: actions/setup-java@v4.1.0
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
      - name: Publish 'internal' subproject
        run: |
          ./gradlew \
          :types4:types-internal:publishAllPublicationsToOSSRHRepository
      - name: Publish root project
        run: |
          ./gradlew :types4:publishAllPublicationsToOSSRHRepository
