name: Dependency submission
on:
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/dependency-submission.yml
      - gradle/libs.versions.toml
      - yarn.lock
  push:
    branches: [ main ]
    paths:
      - .github/workflows/dependency-submission.yml
      - gradle/libs.versions.toml
      - yarn.lock
jobs:
  submit:
    name: Submit to GitHub
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3.1.0
