name: Deployment
on:
  release:
    types: [ released ]
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.11.0
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Generate documentation with Dokka
        run: ./gradlew dokkaHtml --no-daemon
