name: Deployment
on:
  release:
    types: [ released ]
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy API reference
    runs-on: ubuntu-latest
    env:
      BRANCH_TARGET: api-reference
      OLD_DOCS_DIR: library/docs/versions
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.11.0
        with:
          cache: gradle
          distribution: temurin
          java-version: 17
      - name: Get project version
        run: |
          ./gradlew :library:version -q --dry-run
          echo "PROJECT_VERSION=$(./gradlew :library:version -q)" >> "$GITHUB_ENV"
      - name: Get archived API references
        run: |
          git checkout "origin/$BRANCH_TARGET" -- versions && \
          git mv -f versions/* "$OLD_DOCS_DIR/" && \
          rm -r versions/
      - name: Assemble API docs
        run: ./gradlew :library:assembleApiDocs -q
      - name: Archive API reference
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: ${{ env.BRANCH_TARGET }}
          commit-message: "Archive API reference of v${{ env.PROJECT_VERSION }}"
          folder: ${{ env.OLD_DOCS_DIR }}
          ssh-key: ${{ secrets.ADMIN_DEPLOY_KEY }}
          target-folder: versions
      - name: Deploy API reference
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: ${{ env.BRANCH_TARGET }}
          commit-message: "Deploy API reference of v${{ env.PROJECT_VERSION }}"
          folder: build/dokka
          ssh-key: ${{ secrets.ADMIN_DEPLOY_KEY }}
          target-folder: docs
      - name: Remove archived API references
        run: git rm -rf "$OLD_DOCS_DIR/"
