name: Integration (types)
on:
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/integration-types.yml
      - gradle/**
      - subprojects/library/build.gradle.kts
      - subprojects/library/src/**
      - build.gradle.kts
      - gradle.properties
      - gradlew
      - gradlew.bat
      - settings.gradle.kts
      - yarn.lock
  push:
    branches: [ main ]
    paths:
      - .github/workflows/integration-types.yml
      - gradle/**
      - subprojects/library/build.gradle.kts
      - subprojects/library/src/**
      - build.gradle.kts
      - gradle.properties
      - gradlew
      - gradlew.bat
      - settings.gradle.kts
      - yarn.lock
  workflow_dispatch:
env:
  GRADLE_HOME_CACHE_CLEANUP: true
  JAVA_DISTRIBUTION: temurin
  JAVA_VERSION: 17
jobs:
  # --------------------------------- Stage 1 ----------------------------------
  gradle-wrapper-validation:
    name: Gradle checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2.1.2
  # --------------------------------- Stage 2 ----------------------------------
  ubuntu-checks:
    name: Checks on Ubuntu
    needs: gradle-wrapper-validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
        with:
          gradle-home-cache-cleanup: ${{ env.GRADLE_HOME_CACHE_CLEANUP }}
      - name: Check Gradle plugins
        run: ./gradlew :plugins:check
      - name: Test on Kotlin/JS
        run: ./gradlew :types:jsTest
      - name: Test on Kotlin/JVM
        run: ./gradlew :types:jvmTest
      - name: Check Application Binary Interface (ABI) on Kotlin/JVM
        run: ./gradlew :types:apiCheck
      - name: Test on Kotlin/Native
        run: ./gradlew :types:linuxTest
  macos-checks:
    name: Checks on macOS
    needs: gradle-wrapper-validation
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
        with:
          gradle-home-cache-cleanup: ${{ env.GRADLE_HOME_CACHE_CLEANUP }}
      - name: Test on Kotlin/Native for macOS x64
        run: ./gradlew :types:macosTest
  windows-checks:
    name: Checks on Windows
    needs: gradle-wrapper-validation
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2
      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
        with:
          gradle-home-cache-cleanup: ${{ env.GRADLE_HOME_CACHE_CLEANUP }}
      - name: Test on Kotlin/Native for Windows
        run: ./gradlew :types:windowsTest
