# Copyright 2022-2023 Loïc Lamarque, Kotools S.A.S.U.
# Use of this source code is governed by the MIT license.

name: Integration
on:
  pull_request:
    branches: [ main ]
    paths:
      - '**gradle*'
      - '**.kt*'
      - .github/workflows/integration.yml
      - .github/workflows/static-code-analysis.yml
      - qodana.yaml
  push:
    branches: [ main ]
    paths:
      - '**gradle*'
      - '**.kt*'
      - .github/workflows/integration.yml
      - .github/workflows/static-code-analysis.yml
      - qodana.yaml
  workflow_dispatch:
env:
  CACHING: gradle
  JAVA_DISTRIBUTION: temurin
  JAVA_VERSION: 17
jobs:
  # ---------- Stage 1 ----------
  validate-wrapper:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
  # ---------- Stage 2 ----------
  check-api-binaries:
    name: Check API binaries
    needs: validate-wrapper
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.11.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Check API binaries
        run: ./gradlew :apiCheck --no-daemon --quiet
  dependencies:
    name: Submit dependencies to GitHub
    needs: validate-wrapper
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Submit dependencies to GitHub
        uses: mikepenz/gradle-dependency-submission@v0.8.6
        with:
          gradle-build-configuration: allSourceSetsRuntimeDependenciesMetadata
          fail-on-error: true
  js-test:
    name: JS tests
    needs: validate-wrapper
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.11.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Test code
        run: ./gradlew :jsTest --no-daemon --quiet
  jvm-test:
    name: JVM tests
    needs: validate-wrapper
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.11.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Test code
        run: ./gradlew :jvmTest --no-daemon --quiet
  linux-test:
    name: Linux tests
    needs: validate-wrapper
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.11.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Test code
        run: ./gradlew :linuxTest --no-daemon --quiet
  macos-test:
    name: macOS tests
    needs: validate-wrapper
    runs-on: macos-latest
    permissions: read-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.11.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Test code
        run: ./gradlew :macosTest --no-daemon --quiet
  static-code-analysis:
    name: Static code analysis
    needs: validate-wrapper
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Scan code
        uses: JetBrains/qodana-action@v2023.2.8
        with:
          args: --fail-threshold,0
          pr-mode: false
  windows-test:
    name: Windows tests
    needs: validate-wrapper
    runs-on: windows-latest
    permissions: read-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.11.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Test code
        run: ./gradlew :windowsTest --no-daemon --quiet
