name: Integration
on:
  pull_request:
    branches: [ main ]
    paths:
      - '**gradle*'
      - '**.kt*'
      - .github/workflows/integration.yml
  push:
    branches: [ main ]
    paths:
      - '**gradle*'
      - '**.kt*'
      - .github/workflows/integration.yml
  workflow_dispatch:
env:
  CACHING: gradle
  JAVA_DISTRIBUTION: temurin
  JAVA_VERSION: 17
jobs:
  # ---------- Stage 1 ----------
  validate-wrapper:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
  # ---------- Stage 2 ----------
  check-api-binaries:
    name: Check API binaries
    needs: validate-wrapper
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.11.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Check API binaries
        run: ./gradlew -q :library:apiCheck --no-daemon
  dependencies:
    name: Submit dependencies to GitHub
    needs: validate-wrapper
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Submit dependencies to GitHub
        uses: mikepenz/gradle-dependency-submission@v0.8.6
        with:
          gradle-build-configuration: allSourceSetsRuntimeDependenciesMetadata
          gradle-build-module: ":library"
          fail-on-error: true
  test:
    name: Test
    needs: validate-wrapper
    strategy:
      max-parallel: 3
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    permissions: read-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.11.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Test code
        run: ./gradlew -q :library:allTests --no-daemon
