# Copyright 2022-2023 Loïc Lamarque, Kotools S.A.S.U.
# Use of this source code is governed by the MIT license.

name: Integration
on:
  pull_request:
    branches: [ main ]
    paths:
      - '**gradle*'
      - '**.java'
      - '**.kt*'
      - .github/workflows/integration.yml
      - api/types.api
      - qodana.yaml
  push:
    branches: [ main ]
    paths:
      - '**gradle*'
      - '**.java'
      - '**.kt*'
      - .github/workflows/integration.yml
      - api/types.api
      - qodana.yaml
  workflow_dispatch:
env:
  CACHING: gradle
  JAVA_DISTRIBUTION: temurin
  JAVA_VERSION: 17
jobs:
  # ---------- Stage 1 ----------
  static-code-analysis:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Scan code
        uses: JetBrains/qodana-action@v2023.2.8
        with:
          args: --fail-threshold,0
          pr-mode: false
  # ---------- Stage 2 ----------
  gradle-wrapper-validation:
    name: Validate Gradle wrapper
    runs-on: ubuntu-latest
    needs: static-code-analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.6
  # ---------- Stage 3 ----------
  api-binary-check:
    name: API binary check
    needs: gradle-wrapper-validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.11.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Check API binaries
        run: ./gradlew :apiCheck --no-daemon
  java-compatibility-test:
    name: Java compatibility tests
    needs: gradle-wrapper-validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.11.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Test code
        run: ./gradlew :java-compatibility:test --no-daemon
  js-test:
    name: Kotlin/JS tests
    needs: gradle-wrapper-validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.11.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Test code
        run: ./gradlew :jsTest --no-daemon
  jvm-test:
    name: Kotlin/JVM tests
    needs: gradle-wrapper-validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.11.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Test code
        run: ./gradlew :jvmTest --no-daemon
  linux-test:
    name: Kotlin Native tests for Linux
    needs: gradle-wrapper-validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.11.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Test code
        run: ./gradlew :linuxTest --no-daemon
  macos-test:
    name: Kotlin Native tests for macOS
    needs: gradle-wrapper-validation
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.11.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Test code
        run: ./gradlew :macosTest --no-daemon
  windows-test:
    name: Kotlin Native tests for Windows
    needs: gradle-wrapper-validation
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Setup Java & Gradle
        uses: actions/setup-java@v3.11.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: ${{ env.CACHING }}
      - name: Test code
        run: ./gradlew :windowsTest --no-daemon
  # ---------- Stage 4 ----------
  dependencies:
    name: Submit dependencies to GitHub
    needs:
      - api-binary-check
      - java-compatibility-test
      - js-test
      - jvm-test
      - linux-test
      - macos-test
      - windows-test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.0
      - name: Submit dependencies to GitHub
        uses: mikepenz/gradle-dependency-submission@v0.8.6
        with:
          gradle-build-configuration: allSourceSetsRuntimeDependenciesMetadata
          fail-on-error: true
